# This is necessary until https://github.com/travis-ci/travis-ci/issues/3120 is
# fixed
sudo: required

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.10.5
  - 2.11.6

jdk:
  - oraclejdk7
  # Note: not currently testing on JDK 8 internally
  - oraclejdk8
  - openjdk7

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION update

script: ./sbt ++$TRAVIS_SCALA_VERSION coverage test && ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success: ./sbt ++$TRAVIS_SCALA_VERSION coveralls
